<footer class="footer">
  <div class="footer__logo">
    <img class="footer__logo__img" src="/img/feet.png" alt="Ertussenuit: Karel de Grote Hogeschool, Multimedia Technology." />
  </div>

  <ul class="footer__list">
    <li class="footer__list__item footer__list__item--right"><a href="http://multimediatechnology.be"><img src="/img/mta.png" alt="Multimedia Technology Antwerp"></a></li>
    <li class="footer__list__item"><a href="http://kdg.be"><img src="/img/kdg.png" alt="Karel de Grote Hogeschool"></a></li>
  </ul>
</footer>