<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>{{ page.title }}</title>
<meta name="viewport" content="width=device-width">
<!--
           _                                    _ _
  ___ _ __| |_ _   _ ___ ___  ___ _ __  _   _  (_) |_
 / _ \ '__| __| | | / __/ __|/ _ \ '_ \| | | | | | __|
|  __/ |  | |_| |_| \__ \__ \  __/ | | | |_| |_| | |_
 \___|_|   \__|\__,_|___/___/\___|_| |_|\__,_(_)_|\__|

Something wrong?
Find the code at https://github.com/mctantwerpen/ertussenu.it
Fork it, send a pull request on github and we'll fix it together.
-->
<style>
    /* no reset, browser defaults ftw */
    body{
        color:#444;
        padding:1em;
        max-width:40em;
        margin:0 auto;
        font-family: "Helvetica Neue", Helvetica, Arial,sans-serif;
        line-height:1.5;
    }
    img{
        max-width:100%;
    }
    h1, h2, h3, h4, h5, h6, strong{
        color:#505050;
        margin:0 0 0.4em;
        line-height:1.2;
    }
    .sail{
        display:block;
    }
    .feet{
        margin:1em 0 0;
    }
    h1{
        margin:0;
        font-size:2.4em;
    }
    .tagline{
        font-size:1.1em;
        margin:0 0 1em;
    }
    ul, ol, p{
        margin:0 0 1.5em;
    }
    a{
        color:rgb(18, 173, 241);
    }
    li a{
        text-decoration: none;
    }
</style>