<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>{{ page.title }}</title>
<meta name="viewport" content="width=device-width">
<!--
           _                                    _ _
  ___ _ __| |_ _   _ ___ ___  ___ _ __  _   _  (_) |_
 / _ \ '__| __| | | / __/ __|/ _ \ '_ \| | | | | | __|
|  __/ |  | |_| |_| \__ \__ \  __/ | | | |_| |_| | |_
 \___|_|   \__|\__,_|___/___/\___|_| |_|\__,_(_)_|\__|

Something wrong?
Find the code at https://github.com/mctantwerpen/ertussenu.it
Fork it, send a pull request on github and we'll fix it together.
-->
<link rel="stylesheet" href="/css/app.css">